Repository CSID-DGU/2023-2-OSSP2-PM4-4, pull requests merged in 2023-12, with the labels that each got.

#24 Feat/front end/signin
  client/src/App.js
  client/src/DateInput.js
  client/src/layout/Nav.js
  client/src/login/LogInPage.js
  client/src/signin/SignInPage.css
  client/src/signin/SignInPage.js
  client/src/signup/AwardInput.css
  client/src/signup/AwardInput.js
  client/src/signup/IntroductionInput.css
  client/src/signup/ProjectRecordInput.js
  client/src/signup/SignUpPage.js
  client/src/signup/SkillStackInput.js
Labels: :star: new feature

#29 Fix: Change duplicate mapping url
  server/src/main/java/project/manager/server/controller/MyPageController.java
  server/src/main/java/project/manager/server/dto/ResponseDto.java
  server/src/main/java/project/manager/server/dto/exception/ExceptionDto.java
  server/src/main/java/project/manager/server/dto/exception/InvalidateArgumentExceptionDto.java
  server/src/main/java/project/manager/server/dto/exception/JSONConvertExceptionDto.java
  server/src/main/java/project/manager/server/dto/reponse/ReviewDto.java
  server/src/main/java/project/manager/server/dto/reponse/post/building/ApplyDto.java
  server/src/main/java/project/manager/server/dto/reponse/post/building/BuildingPostDto.java
  server/src/main/java/project/manager/server/dto/reponse/region/SiDto.java
  server/src/main/java/project/manager/server/dto/reponse/resume/SchoolDto.java
  server/src/main/java/project/manager/server/dto/request/resume/create/ResumeRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/update/ResumeUpdateDto.java
  server/src/main/java/project/manager/server/exception/GlobalRestExceptionHandler.java
  server/src/main/java/project/manager/server/service/resume/ResumeService.java
Labels: :bug: bug

#31 Fix: bugfix in written review api
  server/src/main/java/project/manager/server/controller/MyPageController.java
  server/src/main/java/project/manager/server/dto/reponse/ReviewDto.java
  server/src/main/java/project/manager/server/repository/ReviewRepository.java
  server/src/main/java/project/manager/server/service/ReviewService.java
Labels: :bug: bug

#34 !HotFix: Costum repository error resolve
  server/build.gradle
  server/src/main/java/project/manager/server/controller/ChatController.java
  server/src/main/java/project/manager/server/controller/MyPageController.java
  server/src/main/java/project/manager/server/controller/RegionController.java
  server/src/main/java/project/manager/server/controller/ResumeController.java
  server/src/main/java/project/manager/server/controller/ReviewController.java
  server/src/main/java/project/manager/server/controller/UserController.java
  server/src/main/java/project/manager/server/controller/manage/BuildingReportController.java
  server/src/main/java/project/manager/server/controller/manage/ContestReportController.java
  server/src/main/java/project/manager/server/controller/manage/ResumeReportController.java
  server/src/main/java/project/manager/server/controller/manage/ReviewReportController.java
  server/src/main/java/project/manager/server/controller/manage/UserReportController.java
  server/src/main/java/project/manager/server/controller/post/ApplyController.java
  server/src/main/java/project/manager/server/controller/post/BuildingPostController.java
  server/src/main/java/project/manager/server/controller/post/ContestPostController.java
  server/src/main/java/project/manager/server/controller/post/PartController.java
  server/src/main/java/project/manager/server/controller/post/PostTypeController.java
  server/src/main/java/project/manager/server/controller/post/ProjectPostController.java
  server/src/main/java/project/manager/server/dto/reponse/ResponseDto.java
  server/src/main/java/project/manager/server/exception/GlobalRestExceptionHandler.java
  server/src/main/java/project/manager/server/repository/post/contest/CustomContestRepositoryImpl.java
  server/src/main/java/project/manager/server/util/Oauth2UserInfo.java
  server/src/main/java/project/manager/server/util/Oauth2Util.java
Labels: :bug: bug

#35 Feat/front end/interlock
  client/public/default.png
  client/src/App.js
  client/src/forum/assets/default.png
  client/src/forum/assets/searchIcon.svg
  client/src/forum/component/List_Category.js
  client/src/forum/component/List_Forum_Category.js
  client/src/forum/component/List_Forums.js
  client/src/forum/component/List_Projects.js
  client/src/forum/component/List_Search.js
  client/src/forum/component/RenderPageNumber.js
  client/src/forum/component/Search.js
  client/src/forum/component/Write_Body.js
  client/src/forum/component/Write_Category.js
  client/src/forum/component/Write_Category_Dropdown.js
  client/src/forum/component/Write_Contest_Dropdown.js
  client/src/forum/component/Write_Title.js
  client/src/forum/component/axios_category.js
  client/src/forum/component/forumList.js
  client/src/forum/component/write_DatePick.js
  client/src/forum/css/Contest_Post_InfoTab.module.css
  client/src/forum/css/Contest_Post_TeamTab.module.css
  client/src/forum/css/Contest_Team_Write(View).module.css
  client/src/forum/css/List.module.css
  client/src/forum/css/List_PageNumber.module.css
  client/src/forum/css/Team_Write(Post).module.css
  client/src/forum/page/Contest_Info_Post.js
  client/src/forum/page/Contest_Info_Write.js
  client/src/forum/page/Contest_List.js
  client/src/forum/page/Contest_ListPage.js
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/forum/page/Contest_Post_TeamTab.js
  client/src/forum/page/Contest_Team_ListTab.js
  client/src/forum/page/Contest_Team_Write(Post).js
  client/src/forum/page/Contest_Team_Write(View).js
  client/src/forum/page/Contest_Write.js
  client/src/forum/page/Project_ListPage.js
  client/src/forum/page/Project_TeamWrite.js
  client/src/forum/page/Team_Write(Post).js
  client/src/layout/List_PageNumber.js
Labels: :star: new feature

#38 Fix: Fix mysql error
  server/src/main/java/project/manager/server/domain/Review.java
  server/src/main/java/project/manager/server/domain/post/building/BuildingPost.java
  server/src/main/java/project/manager/server/enums/Constant.java
  server/src/main/java/project/manager/server/service/ReviewService.java
  server/src/main/java/project/manager/server/service/post/building/BuildingPostService.java
  server/src/main/java/project/manager/server/service/post/building/ProjectPostService.java
Labels: :bug: bug

#40 Feat/front end/mypage
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Cash.js
  client/src/DateInput.js
  client/src/Modal.css
  client/src/ReportModal.css
  client/src/ReportModal.js
  client/src/Siren.js
  client/src/layout/Nav.js
  client/src/layout/StarRate.js
  client/src/layout/StarTest.css
  client/src/layout/StarTest.js
  client/src/mypage/MyPage.css
  client/src/mypage/MyPage.js
  client/src/mypage/MyPageApply.css
  client/src/mypage/MyPageApply.js
  client/src/mypage/MyPageResume.css
  client/src/mypage/MyPageResume.js
  client/src/mypage/MyPageReview.css
  client/src/mypage/MyPageReview.js
  client/src/mypage/MyPageReward.css
  client/src/mypage/MyPageReward.js
  client/src/mypage/MyPageWriteReview.css
  client/src/mypage/MyPageWriteReview.js
  client/src/mypage/MyPageWritten.css
  client/src/mypage/MyPageWritten.js
  client/src/mypage/ReviewModal.js
  client/src/mypage/UserSideBar.css
  client/src/mypage/UserSideBar.js
  client/src/mypage/WithdrawalModal.js
  client/src/signup/EducationInput.js
  client/src/signup/NickNameInput.js
  client/src/signup/ProjectRecordInput.js
  client/src/signup/SignUpPage.js
Labels: :star: new feature

#42 Feat/front end/interlock
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/forum/component/List_Projects.js
  client/src/forum/component/Write_Body.js
  client/src/forum/component/Write_Category.js
  client/src/forum/component/Write_Category_Dropdown.js
  client/src/forum/component/Write_DatePick.js
  client/src/forum/component/axios_category.js
  client/src/forum/css/Team_Write(Post).module.css
  client/src/forum/css/Team_Write(View).module.css
  client/src/forum/css/modal.module.css
  client/src/forum/modal/Write_Apply.js
  client/src/forum/modal/Write_ApplyApprovedList.js
  client/src/forum/modal/Write_ApplyList.js
  client/src/forum/page/Contest_Post_TeamTab.js
  client/src/forum/page/Contest_Write.js
  client/src/forum/page/Team_Write(Edit).js
  client/src/forum/page/Team_Write(Post).js
  client/src/forum/page/Team_Write(View).js
Labels: :star: new feature

#44 Feat/front end/chat
  client/public/defaultProfile.png
  client/public/defaultProfile.svg
  client/src/App.js
  client/src/chat/ChatList.js
  client/src/chat/ChatList.module.css
  client/src/chat/ChatListPage.js
  client/src/chat/ChatLog.js
  client/src/chat/ChatPage.module.css
  client/src/chat/ChatRoom.js
  client/src/forum/component/List_Projects.js
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/forum/page/Team_Write(Post).js
  client/src/layout/Nav.js
Labels: :star: new feature

#45 Fix/front end/review
  client/package-lock.json
  client/src/ReviewPage.js
  client/src/adminpage/BuildingReportList.js
  client/src/adminpage/ContestReportList.js
  client/src/adminpage/ReportList.css
  client/src/adminpage/ResumeReportList.js
  client/src/adminpage/ReviewReportList.js
  client/src/adminpage/UserReportList.js
  client/src/layout/StarRate.js
  client/src/layout/StarTest.css
  client/src/mypage/MyPageReview.js
Labels: :bug: bug

#47 Fix/front end/bugfix
  client/src/Modal.css
  client/src/ReportModal.js
  client/src/UserPage.js
  client/src/chat/ChatList.js
  client/src/chat/ChatLog.js
  client/src/chat/ChatRoom.js
  client/src/forum/component/List_Forum_Category.js
  client/src/forum/component/List_Forums.js
  client/src/forum/css/List.module.css
  client/src/forum/css/buttons.css
  client/src/forum/modal/Write_ApplyList.js
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/forum/page/Team_Write(View).js
Labels: :bug: bug

#48 feat/back-end/chat
  client/src/chat/ChatList.js
  client/src/chat/ChatLog.js
  client/src/chat/ChatRoom.js
  server/src/main/java/project/manager/server/controller/ChatController.java
  server/src/main/java/project/manager/server/domain/User.java
  server/src/main/java/project/manager/server/domain/chat/Chat.java
  server/src/main/java/project/manager/server/domain/chat/ChatRoom.java
  server/src/main/java/project/manager/server/dto/reponse/chat/ChatDto.java
  server/src/main/java/project/manager/server/dto/reponse/chat/ChatRoomDto.java
  server/src/main/java/project/manager/server/dto/request/chat/ChatRequestDto.java
  server/src/main/java/project/manager/server/dto/request/chat/ChatRoomRequestDto.java
  server/src/main/java/project/manager/server/repository/chat/ChatRepository.java
  server/src/main/java/project/manager/server/repository/chat/ChatRoomRepository.java
  server/src/main/java/project/manager/server/service/chat/ChatRoomService.java
  server/src/main/java/project/manager/server/service/chat/ChatService.java
Labels: :star: new feature

#49 Feat: Add resume image profile
  server/build.gradle
  server/src/main/java/project/manager/server/annotation/UserId.java
  server/src/main/java/project/manager/server/annotation/UserIdArgumentResolver.java
  server/src/main/java/project/manager/server/annotation/UserIdInterceptor.java
  server/src/main/java/project/manager/server/configuration/SecurityConfig.java
  server/src/main/java/project/manager/server/controller/ChatController.java
  server/src/main/java/project/manager/server/controller/ResumeController.java
  server/src/main/java/project/manager/server/controller/UserController.java
  server/src/main/java/project/manager/server/domain/Review.java
  server/src/main/java/project/manager/server/domain/User.java
  server/src/main/java/project/manager/server/domain/chat/Chat.java
  server/src/main/java/project/manager/server/domain/chat/ChatRoom.java
  server/src/main/java/project/manager/server/domain/resume/Award.java
  server/src/main/java/project/manager/server/domain/resume/School.java
  server/src/main/java/project/manager/server/dto/reponse/ReviewDto.java
  server/src/main/java/project/manager/server/dto/reponse/chat/ChatDto.java
  server/src/main/java/project/manager/server/dto/reponse/resume/AwardDto.java
  server/src/main/java/project/manager/server/dto/reponse/resume/SchoolDto.java
  server/src/main/java/project/manager/server/dto/request/chat/ChatRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/create/AwardRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/create/ProjectRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/create/ResumeRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/create/SchoolRequestDto.java
  server/src/main/java/project/manager/server/dto/request/resume/update/ResumeUpdateDto.java
  server/src/main/java/project/manager/server/dto/request/resume/update/SchoolUpdateDto.java
  server/src/main/java/project/manager/server/exception/ErrorDefine.java
  server/src/main/java/project/manager/server/repository/UserRepository.java
  server/src/main/java/project/manager/server/repository/chat/ChatRepository.java
  server/src/main/java/project/manager/server/repository/chat/ChatRoomRepository.java
  server/src/main/java/project/manager/server/repository/resume/AwardRepository.java
  server/src/main/java/project/manager/server/repository/resume/SchoolRepository.java
  server/src/main/java/project/manager/server/security/CustomUserDetail.java
  server/src/main/java/project/manager/server/security/CustomUserDetailService.java
  server/src/main/java/project/manager/server/security/JwtAccessDeniedHandler.java
  server/src/main/java/project/manager/server/security/JwtEntryPoint.java
  server/src/main/java/project/manager/server/security/filter/ConstantUrl.java
  server/src/main/java/project/manager/server/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/project/manager/server/security/filter/JwtExceptionFilter.java
  server/src/main/java/project/manager/server/security/jwt/JwtProvider.java
  server/src/main/java/project/manager/server/security/jwt/JwtToken.java
  server/src/main/java/project/manager/server/service/ReviewService.java
  server/src/main/java/project/manager/server/service/UserService.java
  server/src/main/java/project/manager/server/service/chat/ChatRoomService.java
  server/src/main/java/project/manager/server/service/chat/ChatService.java
  server/src/main/java/project/manager/server/service/report/ReviewReportService.java
  server/src/main/java/project/manager/server/service/resume/AwardService.java
  server/src/main/java/project/manager/server/service/resume/ResumeService.java
  server/src/main/java/project/manager/server/service/resume/SchoolService.java
Labels: :star: new feature

#50 !Hotfix
  server/src/main/java/project/manager/server/controller/ResumeController.java
  server/src/main/java/project/manager/server/controller/UserController.java
  server/src/main/java/project/manager/server/controller/post/PartController.java
  server/src/main/java/project/manager/server/domain/User.java
  server/src/main/java/project/manager/server/service/post/building/BuildingPostService.java
  server/src/main/java/project/manager/server/service/post/building/ProjectPostService.java
Labels: :bug: bug

#51 Design/front end/forum
  client/public/backIcon.svg
  client/public/chatSubmit.svg
  client/public/upload.svg
  client/src/Modal.css
  client/src/ReportModal.js
  client/src/chat/ChatList.js
  client/src/chat/ChatList.module.css
  client/src/chat/ChatLog.js
  client/src/chat/ChatPage.module.css
  client/src/chat/ChatRoom.js
  client/src/forum/component/List_Project_Category.js
  client/src/forum/component/List_Projects.js
  client/src/forum/component/Write_Body.js
  client/src/forum/component/Write_Category.js
  client/src/forum/component/Write_Category_Dropdown.js
  client/src/forum/component/Write_Contest_Dropdown.js
  client/src/forum/component/Write_DatePick.js
  client/src/forum/css/Contest_Post_InfoTab.module.css
  client/src/forum/css/Contest_Post_TeamTab.module.css
  client/src/forum/css/List.module.css
  client/src/forum/css/List_PageNumber.module.css
  client/src/forum/css/Team_Write(Post).module.css
  client/src/forum/css/Team_Write(View).module.css
  client/src/forum/css/buttons.css
  client/src/forum/css/modal.module.css
  client/src/forum/modal/Write_Apply.js
  client/src/forum/modal/Write_ApplyApprovedList.js
  client/src/forum/modal/Write_ApplyList.js
  client/src/forum/page/Contest_List.js
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/forum/page/Contest_Write.js
  client/src/forum/page/Project_List.js
  client/src/forum/page/Team_Write(Edit).js
  client/src/forum/page/Team_Write(Post).js
  client/src/forum/page/Team_Write(View).js
Labels: enhancement

#52 Feat: Add image api and apply api
  server/src/main/java/project/manager/server/controller/post/ApplyController.java
  server/src/main/java/project/manager/server/controller/post/ContestPostController.java
  server/src/main/java/project/manager/server/domain/Image.java
  server/src/main/java/project/manager/server/domain/Review.java
  server/src/main/java/project/manager/server/domain/post/building/BuildingPost.java
  server/src/main/java/project/manager/server/domain/post/contest/ContestPost.java
  server/src/main/java/project/manager/server/domain/report/BuildingReport.java
  server/src/main/java/project/manager/server/domain/report/ContestReport.java
  server/src/main/java/project/manager/server/domain/report/ResumeReport.java
  server/src/main/java/project/manager/server/domain/report/ReviewReport.java
  server/src/main/java/project/manager/server/domain/report/UserReport.java
  server/src/main/java/project/manager/server/domain/resume/Project.java
  server/src/main/java/project/manager/server/domain/resume/TechStack.java
  server/src/main/java/project/manager/server/dto/reponse/post/building/ApplyDto.java
  server/src/main/java/project/manager/server/dto/reponse/post/contest/ContestPostDto.java
  server/src/main/java/project/manager/server/dto/reponse/post/contest/ContestTitleDto.java
  server/src/main/java/project/manager/server/repository/post/building/ApplyRepository.java
  server/src/main/java/project/manager/server/repository/post/contest/ContestPostRepository.java
  server/src/main/java/project/manager/server/service/post/building/ApplyService.java
  server/src/main/java/project/manager/server/service/post/contest/ContestPostService.java
Labels: :star: new feature

#53 Feat: Making detailed & fine-grained modifications in an API
  server/src/main/java/project/manager/server/controller/post/ContestPostController.java
  server/src/main/java/project/manager/server/controller/post/PartController.java
  server/src/main/java/project/manager/server/dto/reponse/UserDto.java
  server/src/main/java/project/manager/server/dto/reponse/post/contest/ContestPostDto.java
  server/src/main/java/project/manager/server/dto/request/UserRequestDto.java
  server/src/main/java/project/manager/server/repository/post/building/ApplyRepository.java
  server/src/main/java/project/manager/server/repository/post/building/PartRepository.java
  server/src/main/java/project/manager/server/repository/post/contest/CustomContestRepositoryImpl.java
  server/src/main/java/project/manager/server/service/post/building/BuildingPostService.java
  server/src/main/java/project/manager/server/service/post/building/PartService.java
  server/src/main/java/project/manager/server/service/post/building/ProjectPostService.java
  server/src/main/java/project/manager/server/service/post/contest/ContestPostService.java
Labels: enhancement

#54 Feat/front end/contestSearch
  client/src/forum/component/List_Forums.js
  client/src/forum/css/Contest_Post_InfoTab.module.css
  client/src/forum/css/List.module.css
  client/src/forum/modal/Write_ApplyApprovedList.js
  client/src/forum/page/Contest_List.js
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/forum/page/Contest_Write.js
  client/src/forum/page/Team_Write(Edit).js
  client/src/forum/page/Team_Write(View).js
Labels: enhancement

#55 Fix/front end/totalfix
  client/src/ReportModal.js
  client/src/ReviewPage.js
  client/src/UserPage.js
  client/src/forum/css/Team_Write(Post).module.css
  client/src/forum/page/Contest_Post_InfoTab.js
  client/src/layout/Nav.js
  client/src/main/Ad.js
  client/src/main/Intro.js
  client/src/main/Statistics.js
  client/src/mypage/MyPage.js
  client/src/mypage/MyPageResume.js
  client/src/mypage/MyPageReview.js
  client/src/mypage/MyPageReward.css
  client/src/mypage/MyPageWritten.js
  client/src/signup/AwardInput.js
  client/src/signup/EducationInput.css
  client/src/signup/EducationInput.js
  client/src/signup/NickNameInput.js
  client/src/signup/ProfileImageUpload.js
  client/src/signup/ProjectRecordInput.js
  client/src/signup/RegionInput.js
  client/src/signup/SignUpPage.js
Labels: :bug: bug

#56 Feat/back end/oauth
  server/build.gradle
  server/src/main/java/project/manager/server/annotation/UserIdArgumentResolver.java
  server/src/main/java/project/manager/server/configuration/SecurityConfig.java
  server/src/main/java/project/manager/server/configuration/WebConfig.java
  server/src/main/java/project/manager/server/controller/AuthController.java
  server/src/main/java/project/manager/server/controller/manage/ReviewReportController.java
  server/src/main/java/project/manager/server/dto/reponse/SigninDto.java
  server/src/main/java/project/manager/server/security/CustomUserDetailService.java
  server/src/main/java/project/manager/server/security/jwt/JwtProvider.java
  server/src/main/java/project/manager/server/security/jwt/JwtToken.java
  server/src/main/java/project/manager/server/service/AuthService.java
  server/src/main/java/project/manager/server/util/Oauth2UserInfo.java
  server/src/main/java/project/manager/server/util/Oauth2Util.java
Labels: :star: new feature

#57 feat/back-end/chat
  server/src/main/java/project/manager/server/controller/ChatController.java
  server/src/main/java/project/manager/server/dto/reponse/chat/ChatCreate.java
  server/src/main/java/project/manager/server/repository/chat/ChatRoomRepository.java
  server/src/main/java/project/manager/server/service/chat/ChatRoomService.java
Labels: enhancement

#58 Feat: search api for project post api
  server/src/main/java/project/manager/server/controller/post/ApplyController.java
  server/src/main/java/project/manager/server/controller/post/ProjectPostController.java
  server/src/main/java/project/manager/server/dto/reponse/post/building/ApplyDto.java
  server/src/main/java/project/manager/server/repository/post/building/BuildingPostRepository.java
  server/src/main/java/project/manager/server/service/post/building/ApplyService.java
  server/src/main/java/project/manager/server/service/post/building/BuildingPostService.java
  server/src/main/java/project/manager/server/service/post/building/ProjectPostService.java
Labels: :star: new feature

#59 Feat/back end/oauth
  server/src/main/java/project/manager/server/controller/AuthController.java
  server/src/main/java/project/manager/server/controller/UserController.java
  server/src/main/java/project/manager/server/controller/post/ApplyController.java
  server/src/main/java/project/manager/server/domain/User.java
  server/src/main/java/project/manager/server/domain/post/building/BuildingPost.java
  server/src/main/java/project/manager/server/exception/ErrorDefine.java
  server/src/main/java/project/manager/server/repository/post/building/ApplyRepository.java
  server/src/main/java/project/manager/server/service/AuthService.java
  server/src/main/java/project/manager/server/service/post/building/ApplyService.java
Labels: enhancement

#60 Fix: Fix pin error
  server/src/main/java/project/manager/server/dto/reponse/post/building/BuildingTitleDto.java
  server/src/main/java/project/manager/server/service/post/building/BuildingPostService.java
  server/src/main/java/project/manager/server/service/post/building/ProjectPostService.java
Labels: :bug: bug

#61 Feat: Add social login
  client/package-lock.json
  client/package.json
  client/public/google.svg
  client/src/App.js
  client/src/Google.js
  client/src/forum/component/List_Forum_Category.js
  client/src/signin/GoogleRedirect.js
  client/src/signin/SignInPage.css
  client/src/signin/SignInPage.js
Labels: :star: new feature
